Update: Added the push job to push the tested image to docker hub

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -33,7 +33,7 @@ jobs:
         run: docker save -o $IMAGE_ARTIFACT $IMAGE_NAME
 
       - name: Upload Image Artifact
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v3
         with:
           name: docker-image
           path: ${{ env.IMAGE_ARTIFACT }}
@@ -60,7 +60,34 @@ jobs:
       
       - name: Health Check
         run: |
-          curl --fail http://localhost:3000 || (echo "Health check failed!" && exit 1)
+          curl --fail http://localhost:3000 || (echo " Health check failed!" && exit 1)
       - name: Stop container
         if: always()
         run: docker rm -f temp-container || true
+
+      - name: Save Tested Docker Image as Artifact
+        run: docker save -o $IMAGE_ARTIFACT $IMAGE_NAME
+
+      - name: Upload Image Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: tested-docker-image
+          path: ${{ env.IMAGE_ARTIFACT }}
+  
+  push-image:
+    runs-on: ubuntu-latest
+    needs: test-image
+    steps:
+      - name: Download image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: tested-docker-image
+
+      - name: Load Docker image
+        run: docker load -i $IMAGE_ARTIFACT
+
+      - uses: actions/checkout@v4
+      - name: Log in to DockerHub
+        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin
+      - name: Push Image
+        run: docker push $IMAGE_NAME
