Update docker-image.yml: added the test-image job to perform health check to the image

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -25,3 +25,18 @@ jobs:
       - uses: actions/checkout@v4
       - name: Build Docker Image
         run: docker build -t oreay/nodejs-cicd:1.0 .
+  test-image:
+    runs-on: ubuntu-latest
+    needs: build-image
+    steps:
+      - name: Run container from image
+        run: |
+          docker run -d --name temp-container -p 3000:3000 yourusername/nodejs-cicd:1.0
+      - name: Wait for app to boot
+        run: sleep 10
+      - name: Health Check
+        run: |
+          curl --fail http://localhost:3000 || (echo "❌ Health check failed!" && exit 1)
+      - name: Stop container
+        if: always()
+        run: docker rm -f temp-container || true
